# Generated by Django 5.2.1 on 2025-05-12 02:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReissueLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reissue_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_type', models.CharField(choices=[('선불', '선불'), ('착불', '착불')], default='선불', max_length=10)),
                ('reissue_cost', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reissue_logs', to='cert.certificate')),
            ],
            options={
                'ordering': ['-reissue_date'],
            },
        ),
    ]
