# Generated by Django 5.2 on 2025-04-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reissuelog',
            old_name='certificate',
            new_name='certificate_uuid',
        ),
    ]
