services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    container_name: dev-backend
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/web
      - static:/web/static
    depends_on:
      - db
    ports:
      - 8001:8000

  frontend:
    build: ./frontend
    container_name: dev-frontend
    command: npm start
    ports:
      - 3001:3000
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/web
      - node_modules:/web/node_modules
    depends_on:
      - dev-backend

  db:
    image: postgres:16.1-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: dev-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/web/static
    depends_on:
      - dev-backend
      - dev-frontend
      - dev-db

volumes:
  node_modules:
  postgres_data:
  static: