services:
  backend:
    volumes:
      - ./backend:/web/backend
    env_file:
      - ./.env.dev
    extra_hosts:
      - "certmanager-frontend:host-gateway"

  frontend:
    volumes:
      - ./frontend:/web/frontend
    env_file:
      - ./.env.dev
    environment:
      - WATCHPACK_POLLING=true

  db:
    volumes:
    - db:/web/db

  nginx: {}

volumes:
  db: {}