services:
  backend:
    volumes:
      - ./backend:/web/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    extra_hosts:
      - "certmanager-frontend:host-gateway"

  frontend:
    volumes:
      - ./frontend:/web/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env.dev
    environment:
      - WATCHPACK_POLLING=true

  db:
    volumes:
    - db:/web/db

volumes:
  db: {}