services:
  backend:
    volumes:
      - ./backend:/web/backend
      - backend_data:/web/backend/.local
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    extra_hosts:
      - "certmanager-frontend:host-gateway"

  frontend:
    volumes:
      - ./frontend:/web/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env.dev
    environment:
      - WATCHPACK_POLLING=true

  db:
    volumes:
    - db:/web/db
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev

volumes:
  db:
  backend_data: