services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  client:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    volumes:
      - static_volume:/web/static
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume: