version: '3.9'
services:
  backend:
    container_name: certmanager-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
    - db

  frontend:
    container_name: certmanager-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
    - backend

  db:
    container_name: certmanager-db
    image: postgres:16.1-alpine