services:
  backend:
    volumes:
      - ./backend:/web/backend
    env_file:
      - ./.env.dev

  frontend:
    volumes:
      - ./frontend:/web/frontend
    env_file:
      - ./.env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true

    
  db:
    container_name: certmanager-db
    volumes:
      - db:/web/db

volumes:
  db: