# Generated by Django 5.2.1 on 2025-05-27 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCenter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=255)),
                ('center_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('center_address', models.TextField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('ceo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ceo_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationCenterSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_session', models.PositiveIntegerField()),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('tracking_numbers', models.JSONField(blank=True, default=list)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('issue_status', models.CharField(choices=[('DRAFT', '작성중'), ('ISSUED', '발급완료'), ('DELIVERED', '배송완료')], default='DRAFT', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='center.educationcenter')),
            ],
            options={
                'unique_together': {('education_center', 'center_session')},
            },
        ),
    ]
