# Generated by Django 5.2.1 on 2025-05-12 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_educationcenter_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationcenter',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='educationcenter',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='EducationCenterSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_session', models.CharField(blank=True, max_length=50, null=True)),
                ('education_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='center.educationcenter')),
            ],
        ),
        migrations.RemoveField(
            model_name='educationcenter',
            name='center_session',
        ),
    ]
