# Generated by Django 5.2.1 on 2025-05-12 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_educationcenter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcentersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationcentersession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
