# Generated by Django 5.2.1 on 2025-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_educationcentersession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='center_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='center_tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='ceo_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='manager_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
