# Generated by Django 5.2.1 on 2025-05-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_educationcenter_center_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationcenter',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='educationcentersession',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationcentersession',
            name='tracking_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='educationcentersession',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationcentersession',
            name='center_session',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='educationcentersession',
            name='education_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='center.educationcenter'),
        ),
    ]
