# Generated by Django 5.2 on 2025-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='cert_images/'),
        ),
    ]
