# Generated by Django 5.2 on 2025-05-05 12:14

import api.cert.models.upload_path
import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='copy_file',
            field=models.FileField(blank=True, null=True, storage=utils.storage.OverwriteStorage(), upload_to=api.cert.models.upload_path.certificate_pdf_upload_path),
        ),
    ]
