# Generated by Django 5.2 on 2025-05-06 14:50

import api.cert.services.storage
import utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='copy_file',
            field=models.FileField(blank=True, null=True, storage=api.cert.services.storage.OverwriteStorage(), upload_to=utils.helpers.certificate_copy_file_upload_path),
        ),
    ]
