# Generated by Django 5.2.1 on 2025-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='education_center',
        ),
    ]
