# Generated by Django 5.2 on 2025-05-05 13:48

import api.cert.models.helpers
import api.cert.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='copy_file',
            field=models.FileField(blank=True, null=True, storage=api.cert.services.storage.OverwriteStorage(), upload_to=api.cert.models.helpers.copy_file_upload_path),
        ),
    ]
