# Generated by Django 5.2.1 on 2025-05-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_educationcenter_options_and_more'),
        ('cert', '0002_remove_certificate_education_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='education_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.educationcentersession'),
        ),
    ]
