# Generated by Django 5.2.1 on 2025-05-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0003_certificate_education_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='education_session',
            new_name='center_session',
        ),
    ]
