# Generated by Django 5.2.1 on 2025-05-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0004_rename_education_session_certificate_center_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='center_session',
            new_name='education_session',
        ),
    ]
