# Generated by Django 5.2.1 on 2025-05-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_remove_educationcenter_delivery_address_and_more'),
        ('cert', '0005_rename_center_session_certificate_education_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='education_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.educationcenter'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
