# Generated by Django 5.2.1 on 2025-05-27 00:36

import utils.helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=utils.helpers.user_photo_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_session', models.ManyToManyField(blank=True, related_name='users', to='center.educationcentersession')),
            ],
            options={
                'ordering': ['-user_name'],
            },
        ),
    ]
