# Generated by Django 5.2.1 on 2025-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_educationcenter_options_and_more'),
        ('user', '0002_user_education_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education_center',
        ),
        migrations.AddField(
            model_name='user',
            name='education_sessions',
            field=models.ManyToManyField(blank=True, related_name='users', to='center.educationcentersession'),
        ),
    ]
