# Generated by Django 5.2 on 2025-05-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pdf_url',
        ),
    ]
