# Generated by Django 5.2.1 on 2025-05-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_education_center_user_education_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='education_sessions',
            new_name='education_session',
        ),
    ]
