# Generated by Django 5.2 on 2025-05-06 14:50

import utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=utils.helpers.user_photo_upload_path),
        ),
    ]
